language: c
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bc
  - sudo apt-get install python-rdflib python-yaml
  - sudo apt-get install tidy
#compiler:
#  - clang
#  - gcc
script:
  # Apply TRAVIS=1 to codepolicycheck to make it error out on failures;
  # don't prevent apitest/qecmatest which also do a policy check.
  - TRAVIS=1 make codepolicycheck
  - make tidy-site
  - make apitest
  - make qecmatest
