define: DUK_USE_DEBUG
feature_enables: DUK_OPT_DEBUG
introduced: 1.0.0
default: false
tags:
  - debug
description: >
  Enable debug code in Duktape internals.  Without this option other
  debugging options (such as DUK_USE_DPRINT) have no effect.
