define: DUK_USE_PANIC_SEGFAULT
feature_snippet: |
  #undef DUK_USE_PANIC_SEGFAULT
  #if defined(DUK_OPT_SEGFAULT_ON_PANIC)
  #define DUK_USE_PANIC_SEGFAULT
  #endif
introduced: 1.0.0
default: false
tags:
  - portability
description: >
  Cause an intentional segfault when the default panic handler is invoked.
  This is useful when debugging with valgrind because a segfault provides
  a nice C traceback in valgrind.
