define: DUK_USE_FASTINT
feature_snippet: |
  /* Support for 48-bit signed integer duk_tval with transparent semantics. */
  #undef DUK_USE_FASTINT
  #if defined(DUK_OPT_FASTINT)
  #if !defined(DUK_F_HAVE_64BIT)
  #error DUK_OPT_FASTINT requires 64-bit integer type support at the moment
  #endif
  #define DUK_USE_FASTINT
  #endif
related_feature_defines:
  - DUK_OPT_FASTINT
introduced: 1.2.0
default: false
tags:
  - performance
  - fastpath
description: >
  Enable support for 48-bit signed "fastint" integer values.  Fastints are
  transparent to user code (both C and Ecmascript) but may be faster than
  IEEE doubles on some platforms, especially those using softints.  The
  downside of fastints is increased code footprint and a small performance
  penalty for some kinds of code.
