# Enable compliant behavior, defaults favor "real world" compatibility.

DUK_USE_NONSTD_ARRAY_CONCAT_TRAILER: false
DUK_USE_NONSTD_ARRAY_MAP_TRAILER: false
DUK_USE_NONSTD_ARRAY_SPLICE_DELCOUNT: false
DUK_USE_NONSTD_FUNC_CALLER_PROPERTY: false
DUK_USE_NONSTD_FUNC_SOURCE_PROPERTY: false
DUK_USE_NONSTD_FUNC_STMT: false
DUK_USE_NONSTD_GETTER_KEY_ARGUMENT: false
DUK_USE_NONSTD_JSON_ESC_U2028_U2029: false
DUK_USE_NONSTD_SETTER_KEY_ARGUMENT: false
DUK_USE_NONSTD_STRING_FROMCHARCODE_32BIT: false
DUK_USE_ES6_REGEXP_SYNTAX: false  # for ES5 compliance, disable ES6-only regexp extra syntax
